name: Check-and-build Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        id: lint
        run: |
          npm run lint > lint.log 2>&1 || true
          tail -n 50 lint.log
          echo "lint_result<<EOF" >> $GITHUB_OUTPUT
          tail -n 50 lint.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Prettier check
        id: prettier
        run: |
          npm run format:check > prettier.log 2>&1 || true
          tail -n 50 prettier.log
          echo "prettier_result<<EOF" >> $GITHUB_OUTPUT
          tail -n 50 prettier.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run typescript type checks
        id: typecheck
        run: |
          npm run typecheck > typecheck.log 2>&1 || true
          tail -n 50 typecheck.log
          echo "typecheck_result<<EOF" >> $GITHUB_OUTPUT
          tail -n 50 typecheck.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        id: build
        run: |
          npm run build:ci > build.log 2>&1 || true
          tail -n 50 build.log
          echo "build_result<<EOF" >> $GITHUB_OUTPUT
          tail -n 50 build.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate summary for PR
        run: |
          echo '### CI Summary' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '✅ Проверка завершена!' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '#### Линтинг:' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.lint.outputs.lint_result }}" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '#### Prettier:' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.prettier.outputs.prettier_result }}" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '#### Typecheck:' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.typecheck.outputs.typecheck_result }}" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '#### Build:' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build.outputs.build_result }}" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo "- [Логи CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY

      - name: Comment PR with check result
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: check-result
          message: |
            ✅ Проверка завершена!
            
            #### Линтинг:
            ${{ steps.lint.outputs.lint_result }}
            
            #### Prettier:
            ${{ steps.prettier.outputs.prettier_result }}
            
            #### Typecheck:
            ${{ steps.typecheck.outputs.typecheck_result }}
            
            #### Build:
            ${{ steps.build.outputs.build_result }}
            
            [Логи CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
