name: Cleanup Feature Preview

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Extract branch name
        id: extract-branch
        run: |
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "branch=${PR_BRANCH}" >> $GITHUB_OUTPUT
          echo "Branch to cleanup: ${PR_BRANCH}"

      - name: Remove preview directory
        run: |
          BRANCH_PATH="${{ steps.extract-branch.outputs.branch }}"
          echo "Removing preview directory for branch: ${BRANCH_PATH}"
          
          if [ -d "preview/${BRANCH_PATH}" ]; then
            rm -rf "preview/${BRANCH_PATH}"
            echo "✅ Preview directory removed successfully"
          else
            echo "⚠️ Preview directory not found, nothing to remove"
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add -A
          
          # Если есть изменения, коммитим их
          git diff --quiet && git diff --staged --quiet || git commit -m "Cleanup preview for branch ${{ steps.extract-branch.outputs.branch }}"
          
          # Пушим изменения
          git push
